fix/ login + sponsor
incridea-23/incridea-client pull request #106
Opened 2024-02-02 16:32 UTC by Prabhuomkar9

frmaer -> lenis + gsap
autofill bg
error/ succes msg vanish on card change

2024-02-02 18:02 UTC, Aniruddha-Upadhya-K requested changes
Please fix merge conflicts

2024-02-03 09:16 UTC, Prabhuomkar9 commented
@jevil25 has to add XP to user after sign in successfull in signInForm

2024-02-03 09:29 UTC, nandanpi approved these changes

2024-02-03 09:32 UTC, merged

2024-02-03 09:41 UTC, jevil25 commented
> @jevil25 has to add XP to user after sign in successfull in signInForm

I added that it's merged with main
Bomb xp right?