Gallery branch
incridea-23/incridea-client pull request #88
Opened 2024-01-31 17:36 UTC by Exgene

## Features
- Updated gallery page for 2024
- Space gamey themed
- Game styles components
- Preview component for better viewing
- Custom loading bar

## Breaking Changes
- Update the Cloudinary URL
- Update the year array accordingly in `page/gallery/index.tsx`
- Look for potential bugs
- Custom keyframes and animation added in `tailwind.config.ts`
- Tooltip to be added

2024-01-31 17:59 UTC, Aniruddha-Upadhya-K approved these changes

2024-01-31 19:00 UTC, swasthikshetty10 approved these changes

2024-02-01 04:09 UTC, nagarajpandith approved these changes

2024-02-01 04:40 UTC, nagarajpandith requested changes

2024-02-01 04:40 UTC, nagarajpandith commented on src/components/galleryslide/devices/final-component.tsx
> +        src={"/assets/png/4.png"}
should be
```       
src={"/assets/png/dice.png"}
```

2024-02-01 04:40 UTC, nagarajpandith commented on src/components/galleryslide/progressBar/progress-bar.tsx
> +              src={`/assets/png/${index + 1}.png`}
should be
```
src={`/assets/png/level${index === 0 ? "" : index}.png`}
```

2024-02-01 04:45 UTC, nagarajpandith commented
Wanted to confirm whether the Blue progressbar hidden behind navbar is intentional? @Exgene 
It is from swiper's pagination progressbar

<img width="1440" alt="Screenshot 2024-02-01 at 10 14 04 AM" src="https://github.com/incridea-23/incridea-client/assets/83623339/dd453149-96c0-49a8-a96e-09eb10443de4">

2024-02-01 13:07 UTC, Exgene commented
> Wanted to confirm whether the Blue progressbar hidden behind navbar is intentional? @Exgene It is from swiper's pagination progressbar
> 
> <img alt="Screenshot 2024-02-01 at 10 14 04 AM" width="1440" src="https://private-user-images.githubusercontent.com/83623339/301387730-dd453149-96c0-49a8-a96e-09eb10443de4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTI5NjEsIm5iZiI6MTcwNjc5MjY2MSwicGF0aCI6Ii84MzYyMzMzOS8zMDEzODc3MzAtZGQ0NTMxNDktOTZjMC00OWE4LWE5NmUtMDllYjEwNDQzZGU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDEzMDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNDExYTgxYmEwOWQ1OGRlMzJhNmQ3Mjc3ZWE3ZjUzYmNlNGNjODQzYzQzMDc5ZDJkMmE3YzBhZWQ1Nzg1NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eDszqf1KecLsBkeEfz81Q2D4Ct9xqG_g_HdoloE0prA">

Yes i think its fine, Looks nice for the backdrop blur of the navbar, Can change color to match the main color scheme!

2024-02-01 13:10 UTC, Exgene commented on src/components/galleryslide/progressBar/progress-bar.tsx
> +              src={`/assets/png/${index + 1}.png`}
Oh no my assets are missing from here, Logic was fine. Will commit with a fix

2024-02-01 16:26 UTC, nagarajpandith approved these changes

2024-02-01 16:30 UTC, merged